### ISSUE TITLE
OAuth needed

### ISSUE THREAD

**Issue by Artanicus** [dkhmelenko/Varis-Android#45]
Asking for GitHub credentials is not acceptable.

**Comment by dkhmelenko** [comment]
This is the way how Travis API v2 was implemented. The app itself doesn't store any credentials, only tokens.
There is a plan to migrate to API v3 and hopefully we don't need to have GitHub credentials anymore.

**Comment by dkhmelenko** [comment]
@Artanicus Could you please confirm if #47 is the same as your request?

**Comment by dkhmelenko** [comment]
Duplicate of #47
